import { describe, it } from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import path from 'node:path';

describe('map panel search overlay', () => {
  it('renders a submit-based places search form on the map', async () => {
    const panelPath = path.join(process.cwd(), 'components', 'MapPanel.tsx');
    const source = await readFile(panelPath, 'utf-8');

    assert.match(source, /mapSearchQuery,/);
    assert.match(source, /mapSearchScope,/);
    assert.match(source, /setMapSearchScope,/);
    assert.match(source, /mapSearchSort,/);
    assert.match(source, /setMapSearchSort,/);
    assert.match(source, /mapSearchAreaDirty,/);
    assert.match(source, /isSearchingMapLocation,/);
    assert.match(source, /placeSearchResults,/);
    assert.match(source, /searchResultTagDrafts,/);
    assert.match(source, /expandedSearchResultEditorId,/);
    assert.match(source, /activeSearchResultId,/);
    assert.match(source, /savingSearchResultId,/);
    assert.match(source, /handleLoadSearchResultPhotos,/);
    assert.match(source, /searchLocationError,/);
    assert.match(source, /handleSearchMapLocation,/);
    assert.match(source, /handleSearchVisibleArea,/);
    assert.match(source, /handleClearSearchLocation,/);
    assert.match(source, /handleSetSearchResultTag,/);
    assert.match(source, /handleFocusSearchResult,/);
    assert.match(source, /handlePreviewSearchResult,/);
    assert.match(source, /handleOpenSearchResultTagEditor,/);
    assert.match(source, /handleApplySearchShortcut,/);
    assert.match(source, /handleSaveSearchResultAsSpot,/);
    assert.match(source, /const searchResultsContainerRef = useRef\(null\);/);
    assert.match(source, /function SearchResultCard\(\{/);
    assert.match(source, /new IntersectionObserver/);
    assert.match(source, /root: observerRootRef\.current \|\| null/);
    assert.match(source, /void handleLoadSearchResultPhotos\(result\.id\);/);
    assert.match(source, /primaryPhoto\?\.uri/);
    assert.match(source, /<img/);
    assert.match(source, /loading="lazy"/);
    assert.match(source, /const \[showAdvancedSearch, setShowAdvancedSearch\] = useState\(false\);/);
    assert.match(source, /<form/);
    assert.match(source, /void handleSearchMapLocation\(mapSearchQuery\);/);
    assert.match(source, /TRY "CAFE NEARBY" OR "SUSHI MISSION"/);
    assert.match(source, /\{'\/\/ Search Location'\}/);
    assert.match(source, /Searches return multiple pinned places\./);
    assert.match(source, /Advanced Search/);
    assert.match(source, /onClick=\{\(\) => setShowAdvancedSearch\(\(prev\) => !prev\)\}/);
    assert.match(source, /\{showAdvancedSearch \? \(/);
    assert.match(source, /Around Map/);
    assert.match(source, /Near Me/);
    assert.match(source, /Near Home/);
    assert.match(source, /Search This Area/);
    assert.match(source, /Best Match/);
    assert.match(source, /Distance/);
    assert.match(source, /Walk Time/);
    assert.match(source, /Coffee/);
    assert.match(source, /Bars/);
    assert.match(source, /Brunch/);
    assert.match(source, /Parks/);
    assert.match(source, /Museums/);
  });

  it('shows per-result save controls when places search results exist', async () => {
    const panelPath = path.join(process.cwd(), 'components', 'MapPanel.tsx');
    const source = await readFile(panelPath, 'utf-8');

    assert.match(source, /hasSearchLocation,/);
    assert.match(source, /\{hasSearchLocation \? \(/);
    assert.match(source, /savedEntries\.map\(\(\{ result, index \}\) => \{/);
    assert.match(source, /unsavedEntries\.map\(\(\{ result, index \}\) => \{/);
    assert.match(source, /const savedResults = placeSearchResults\.filter/);
    assert.match(source, /const unsavedResults = placeSearchResults\.filter/);
    assert.match(source, /handleSetSearchResultTag\(result\.id, value\)/);
    assert.match(source, /handleFocusSearchResult\(result\.id\)/);
    assert.match(source, /handleSaveSearchResultAsSpot\(result\.id\)/);
    assert.match(source, /handleDeleteCustomSpot\(result\.savedSpotId\)/);
    assert.match(source, /handleOpenSearchResultTagEditor\(result\.id\)/);
    assert.match(source, /onMouseEnter=\{handleActivateCard\}/);
    assert.match(source, /onFocusCapture=\{handleActivateCard\}/);
    assert.match(source, /id=\{`search-result-\$\{result\.id\}`\}/);
    assert.match(source, /searchResultsContainerRef/);
    assert.match(source, /observerRootRef=\{searchResultsContainerRef\}/);
    assert.match(source, /Save Spot/);
    assert.match(source, /Remove Spot/);
    assert.match(source, /Open Map/);
    assert.match(source, /Saved Results/);
    assert.match(source, /Unsaved Results/);
    assert.match(source, /Change Tag/);
    assert.match(source, /Update Tag/);
    assert.match(source, /onClick=\{handleClearSearchLocation\}/);
    assert.match(source, /aria-label="Clear search pin"/);
  });
});
